spring:
  application:
    name: employee_demo
    security:
      jwt:
        access_token:
          secret: ${JWT_ACCESS_TOKEN_SECRET}
          expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
        refresh_token:
          secret: ${JWT_REFRESH_TOKEN_SECRET}
          expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect